version: "3.8"

services:
  backend:
    container_name: myapp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHONUNBUFFERED: 1
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app            
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: myapp-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app                
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - CHOKIDAR_USEPOLLING=true  
    networks:
      - app-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30
